version: "3"
services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - .:/app
    depends_on:
      - php-fpm
    ports:
      - "8003:80"
  php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - .:/app

  mysql:
    image: mariadb:10.4
    ports:
      - 3366:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./databases/mariadb:/var/lib/mysql


  adminer:
    image: adminer
    ports:
      - 8880:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
